#!/usr/bin/env python3
"""gen_morph_tab.py [MSTTSLoc_OneCore.dll] > src/zf1_morph_tab.h

Extracts the CEnMorph tables from the Loc DLL (MSTTSLoc_OneCore.dll 10.3.21207.0):
  loc!0x1800866b0  33 x 0x1c  suffix table {int rule; wchar suffix[10]; int len}
  loc!0x1800a7430  32 x 0x90  rules {wchar phones[20]; {wchar* fromPOS, wchar* toPOS, u16, u16, pad}[4]; short n; int flags}
  loc!0x1800a8630  u32 flag + 17 phone-string pointers (+8 .. +0x88)
The strings are phone/POS *names*; zf1_morph.c converts them with the phone set / lexicon attribute names at init
(the engine converts them in place at FUN_18000dfa0)."""
import sys, struct, pefile

path = sys.argv[1] if len(sys.argv) > 1 else r'D:/llm-experiments/misk/zira/bin/MSTTSLoc_OneCore.dll'
pe = pefile.PE(path, fast_load=True)
img = pe.get_memory_mapped_image()
B = pe.OPTIONAL_HEADER.ImageBase


def ws(r):
    e = r
    while img[e:e + 2] != b'\0\0':
        e += 2
    return img[r:e].decode('utf-16le')


def cstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


out = []
out.append('/* zf1_morph_tab.h - generated by tools/gen_morph_tab.py from MSTTSLoc_OneCore.dll (CEnMorph tables). */')
out.append('static const struct { int rule; const char *suffix; int len; } zf1_morph_suffix[33] = {')
for i in range(33):
    r = 0x866b0 + i * 0x1c
    rid = struct.unpack_from('<i', img, r)[0]
    s = ws(r + 4)
    ln = struct.unpack_from('<I', img, r + 0x18)[0]
    out.append('    {%d, %s, %d},' % (rid, cstr(s), ln))
out.append('};')
out.append('static const struct { const char *phones; int n; const char *from[4], *to[4]; unsigned flags; } '
           'zf1_morph_rule[32] = {')
for k in range(32):
    r = 0xa7430 + k * 0x90
    ph = ws(r)
    n = struct.unpack_from('<h', img, r + 0x88)[0]
    fl = struct.unpack_from('<I', img, r + 0x8c)[0]
    fr, to = [], []
    for j in range(4):
        a, b = struct.unpack_from('<QQ', img, r + 0x28 + 0x18 * j)
        fr.append(cstr(ws(a - B)) if a and j < n else 'NULL')
        to.append(cstr(ws(b - B)) if b and j < n else 'NULL')
    out.append('    {%s, %d, {%s}, {%s}, 0x%x},' % (cstr(ph), n, ', '.join(fr), ', '.join(to), fl))
out.append('};')
out.append('/* pron table (index = byte offset / 8 - 1: +8 .. +0x88) */')
out.append('static const char *const zf1_morph_ptab[17] = {')
for i in range(8, 0x90, 8):
    p = struct.unpack_from('<Q', img, 0xa8630 + i)[0]
    out.append('    %s,  /* +0x%x */' % (cstr(ws(p - B)), i))
out.append('};')
print('\n'.join(out))
