#!/usr/bin/env python3
"""gen_zf1_chartab.py - extract the engine's internal character-class tables from MSTTSEngine_OneCore.dll
(10.3.21207.0) into src/zf1_ss_tab.h for the portable sentence separator (zf1_ss.c).

Tables:
  - DAT_180180820: 256-byte Latin-1 ctype table (1 upper, 2 lower, 4 digit, 8 space, 0x10 punct, 0x20 control,
    0x40 letter/hex-ish, 0x80 vowel)
  - FUN_180072dbc: 32-bit Unicode class for chars >= 0x100 (page table 0x180171e80: 256 x {u16 kind, u16 count,
    u32 pad, u64 ptr}; kind 1 = constant value (low dword of ptr), kind 2 = 256-byte index page, kind 3 = sorted
    {u8 upper_bound, u8 index} pairs; index -> u32 value table 0x180192970).  Emulated here for all 65536 code
    units and stored as a 2-level table.
  - DAT_180193c50: 256-byte Latin-1 base-letter map (accent stripping).
  - UCRT iswdigit / iswspace (the engine calls ucrtbase _o_iswdigit / _o_iswspace): read from a probe dump
    made by tools/ucrt_ctype_probe.c (build with cl /MD, run, pass probe.bin) and stored as bitsets.
Usage: gen_zf1_chartab.py [probe.bin]   (probe.bin = 2 x 8192-byte bitsets: iswdigit, iswspace)
"""
import pefile, struct, sys, os

DLL = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'bin', 'MSTTSEngine_OneCore.dll')
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'zf1_ss_tab.h')
pe = pefile.PE(DLL, fast_load=True)
img = pe.get_memory_mapped_image()
B = 0x180000000
u8 = lambda a: img[a - B]
u16 = lambda a: struct.unpack_from('<H', img, a - B)[0]
u32 = lambda a: struct.unpack_from('<I', img, a - B)[0]
u64 = lambda a: struct.unpack_from('<Q', img, a - B)[0]


def cls_exact(c):
    """literal transliteration of FUN_180072dbc (binary search part included)"""
    hi, lo = c >> 8, c & 0xff
    kind = u16(0x180171e80 + hi * 16)
    cnt = u16(0x180171e82 + hi * 16)
    ptr = u64(0x180171e88 + hi * 16)
    if kind == 1:
        return ptr & 0xffffffff
    if kind == 2:
        idx = u8(ptr + lo)
    elif cnt < 4:
        p = ptr
        while u8(p) < lo:
            p += 2
        idx = u8(p + 1)
    else:
        u3 = 0
        u6 = cnt
        while True:
            while True:
                u5 = u3
                if u6 <= u3:
                    idx = u8(ptr + u5 * 2 + 1)
                    return u32(0x180192970 + idx * 4)
                u5 = (u6 + u3) >> 1
                if lo <= u8(ptr + u5 * 2):
                    break
                u3 = u5 + 1
            u6 = u5
            if not (lo < u8(ptr + u5 * 2)):
                break
        idx = u8(ptr + u5 * 2 + 1)
    return u32(0x180192970 + idx * 4)


def main():
    vals = [cls_exact(c) for c in range(0x10000)]
    uniq = sorted(set(vals))
    vi = {v: i for i, v in enumerate(uniq)}
    assert len(uniq) < 256
    pages = []
    pmap = []
    for p in range(256):
        page = bytes(vi[vals[p * 256 + k]] for k in range(256))
        if page not in pages:
            pages.append(page)
        pmap.append(pages.index(page))
    t820 = bytes(img[0x180820:0x180820 + 256])
    t3c50 = bytes(img[0x193c50:0x193c50 + 256])
    probe = open(sys.argv[1], 'rb').read() if len(sys.argv) > 1 else None
    o = []
    o.append('/* zf1_ss_tab.h - GENERATED by tools/gen_zf1_chartab.py from MSTTSEngine_OneCore.dll 10.3.21207.0\n'
             ' * (character-class data used by the engine\'s tokenizer / sentence separator) and from a UCRT\n'
             ' * iswdigit/iswspace probe.  Do not edit. */')
    o.append('#ifndef ZF1_SS_TAB_H\n#define ZF1_SS_TAB_H\n#include <stdint.h>')

    def bytes_arr(name, b, typ='uint8_t'):
        s = ['static const %s %s[%d] = {' % (typ, name, len(b))]
        for i in range(0, len(b), 16):
            s.append('    ' + ','.join('0x%02x' % x for x in b[i:i + 16]) + ',')
        s.append('};')
        o.append('\n'.join(s))

    bytes_arr('zf1_ctype820', t820)
    bytes_arr('zf1_base3c50', t3c50)
    o.append('static const uint32_t zf1_ucls_val[%d] = {%s};' % (len(uniq), ','.join('0x%08x' % v for v in uniq)))
    bytes_arr('zf1_ucls_pmap', bytes(pmap))
    s = ['static const uint8_t zf1_ucls_pages[%d][256] = {' % len(pages)]
    for pg in pages:
        s.append('  {' + ','.join('%d' % x for x in pg) + '},')
    s.append('};')
    o.append('\n'.join(s))
    if probe:
        bytes_arr('zf1_iswdigit_bits', probe[:8192])
        bytes_arr('zf1_iswspace_bits', probe[8192:16384])
    o.append('#endif')
    open(OUT, 'w').write('\n\n'.join(o) + '\n')
    print('pages', len(pages), 'values', len(uniq))


if __name__ == '__main__':
    main()
