"""Generate src/zb_voctab.h: band FIRs and default band weights read from MSTTSEngine_OneCore.dll, and the 1024-sample
noise table computed exactly as FUN_18006b550 does (UCRT rand/sin/log/sqrt; run on Windows so math.* is the UCRT)."""
import struct, math, sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vocoder_model import dll_tables, CRand, f32
bands, w16, w8 = dll_tables()
r = CRand(); r.srand(0x406); noise = []
for i in range(1024):
    r1 = r.rand(); r2 = r.rand()
    s = math.sin(float(f32(f32(r2 + 1) * f32(1 / 32768.0))) * 6.283185307179586)
    l = math.log(float(f32(f32(r1 + 1) * f32(1 / 32768.0))))
    noise.append(f32(s * math.sqrt(l * -2.0)))
o = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'zb_voctab.h'), 'w')
o.write('/* zb_voctab.h - vocoder constant tables (generated by tools/gen_voctab.py).\n'
        ' * zb_band41: the 5 x 41-tap band-split FIRs of the SPS excitation (engine data at VA 0x18017d3c0, double).\n'
        ' * zb_band_w16k / zb_band_w8k: default band voicing strengths (0x1801927f8 / 0x1801927d0).\n'
        ' * zb_noise1024: the 1024-sample Box-Muller noise table FUN_18006b550 builds after srand(0x406) with the UCRT\n'
        ' *   rand/sin/log/sqrt (float bit patterns), embedded so that no libm call is needed at init. */\n')
o.write('static const double zb_band41[5][41] = {\n')
for b in range(5): o.write('  {' + ', '.join(repr(float(x)) for x in bands[b]) + '},\n')
o.write('};\n')
o.write('static const double zb_band_w16k[5] = {%s};\n' % ', '.join(repr(x) for x in w16))
o.write('static const double zb_band_w8k[5] = {%s};\n' % ', '.join(repr(x) for x in w8))
o.write('static const uint32_t zb_noise1024[1024] = {\n')
hx = ['0x%08x' % struct.unpack('<I', struct.pack('<f', x))[0] for x in noise]
for i in range(0, 1024, 8): o.write('  ' + ', '.join(hx[i:i + 8]) + ',\n')
o.write('};\n')

# ---- fixed-point tables (Zira/Mark): src/zb_voctab_int.h
import pefile
pe = pefile.PE(r'D:/llm-experiments/misk/zira/bin/MSTTSEngine_OneCore.dll', fast_load=True)
img = pe.get_memory_mapped_image(); ib = pe.OPTIONAL_HEADER.ImageBase
def tab(va, n): return struct.unpack_from('<%dh' % n, img, va - ib)
o = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'zb_voctab_int.h'), 'w')
o.write('/* zb_voctab_int.h - fixed-point tables of the int SPS path (generated by tools/gen_voctab.py from MSTTSEngine_OneCore.dll).\n'
        ' * zb_cos2048: DAT_1801866d0 ~ round(32767 cos(2 pi i / 4096)); zb_exp1331: DAT_1801876d0 ~ exp(i/128) (gain);\n'
        ' * zb_f0exp800: DAT_180188140, log-F0 (Q15 >> 8) -> F0 in Hz (FUN_1800ad804). */\n')
for name, va, n in (('zb_cos2048', 0x1801866d0, 2048), ('zb_exp1331', 0x1801876d0, 1331), ('zb_f0exp800', 0x180188140, 800)):
    v = tab(va, n)
    o.write('static const short %s[%d] = {\n' % (name, n))
    for i in range(0, n, 16): o.write('  ' + ', '.join(str(x) for x in v[i:i + 16]) + ',\n')
    o.write('};\n')
o.close()
